### ISSUE TITLE
Problem with  get_token() 

### ISSUE THREAD

**Issue by ucsky** [artefactory/one-click-mlflow#75]
**Describe the bug**

I have the following error when I try to test the one-click-mlflow

```
(venv) ucsky@machine:~/try/one-click-mlflow$ python examples/track_experiment.py 
Enter your project ID: ofi-ai-try
Enter the name of your MLFlow experiment: test
Traceback (most recent call last):
  File "/home/ucsky/try/one-click-mlflow/examples/track_experiment.py", line 5, in <module>
    import mlflow_config
  File "/home/ucsky/try/one-click-mlflow/examples/mlflow_config.py", line 61, in <module>
    os.environ["MLFLOW_TRACKING_TOKEN"] = get_token()
  File "/home/ucsky/try/one-click-mlflow/examples/mlflow_config.py", line 17, in get_token
    token = _get_token()
  File "/home/ucsky/try/one-click-mlflow/examples/mlflow_config.py", line 35, in _get_token
    open_id_connect_token = id_token.fetch_id_token(Request(), client_id)
  File "/home/ucsky/try/one-click-mlflow/examples/venv/lib/python3.9/site-packages/google/oauth2/id_token.py", line 252, in fetch_id_token
    credentials = service_account.IDTokenCredentials.from_service_account_info(
  File "/home/ucsky/try/one-click-mlflow/examples/venv/lib/python3.9/site-packages/google/oauth2/service_account.py", line 528, in from_service_account_info
    signer = _service_account_info.from_dict(
  File "/home/ucsky/try/one-click-mlflow/examples/venv/lib/python3.9/site-packages/google/auth/_service_account_info.py", line 46, in from_dict
    missing = keys_needed.difference(six.iterkeys(data))
  File "/home/ucsky/try/one-click-mlflow/examples/venv/lib/python3.9/site-packages/six.py", line 599, in iterkeys
    return iter(d.keys(**kw))
AttributeError: 'NoneType' object has no attribute 'keys'

```

**To Reproduce**
Installing with
`make one-click-mlflow`
and after
```
cd examples
python3 -m venv venv 
source venv/bin/activate
pip install -r requirements.txt
python track_experiment.py
```

**Expected behavior**
Experiment tracking in MLFlow.

**Desktop (please complete the following information):**
 ```
lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute
```

**Comment by AlexisVLRT** [comment]
Thanks for your feedback!

Did you make sure you input the project ID and not the project name? Sometime they can be different. Both are available in your GCP project homepage in the "Project info" widget.

It it is indeed the right project ID, could you tell me what is in the variables `client_id` and `trackning_uri` line 34 in `examples/mlflow_config.py`?

Thank you!

**Comment by ucsky** [comment]
Yes you are right about the inversion between `client_id` and `tracking_url`, I made an edit to fix this.

Yes I'm able to reach the MLFlow fronted in the browser and everything look fine.
